### ISSUE TITLE
Assigning const char* to auto variable makes Cflat error out because of invalid assignement

### ISSUE THREAD

**Issue by mundusnine** [arturocepeda/Cflat#13]
```c++
//In Script file
auto test = "Test";
```
You can see the behavior here in this [video](https://www.twitch.tv/videos/2082039940?t=0h19m15s)

master commit version used: e12b1a0410e28ce67acca109f8c9e203a690a52d

**Comment by arturocepeda** [comment]
Thanks for reporting the issue, @mundusnine!

'auto' has not been used very much for scripting in the projects I have been involved in, and it surely needs some love. I'll look into it!

**Comment by arturocepeda** [comment]
Update: please pull and try again, 'auto' should now work with string literals.

**Comment by mundusnine** [comment]
Fixed with latest commit
