### ISSUE TITLE
Single char expressions are not supported

### ISSUE THREAD

**Issue by mundusnine** [arturocepeda/Cflat#17]
Doing this: `char singleChar = '_';` will create a Compile Error:
![image](https://github.com/arturocepeda/Cflat/assets/29337013/c316f6ee-97f0-44b8-9c61-68dd9c195c55)

Basically, single chars aren't supported in the tokenizer right now, in that case what happens is it gets parsed as an Identifier.

**Comment by arturocepeda** [comment]
Right, character literals are not supported yet. Will add that!

**Comment by arturocepeda** [comment]
Character literals should now be supported.

**Comment by mundusnine** [comment]
This fixed it. Thank you.
